---
- hosts: all
  become: yes
  vars_files:
  - env_variables
  tasks:

  - copy:
       src: "/home/{{ user }}/.ssh/google_compute_engine"
       dest: "/home/{{ user }}/.ssh/google_compute_engine"
       owner: "{{ user }}"
       group: "{{ user }}"
       mode: 0600

  - name: Install wget
    yum: pkg=wget state=present

  - name: Disabling Swap on all nodes
    shell: swapoff -a

  - name: Commenting Swap entries in /etc/fstab
    replace:
     path: /etc/fstab
     regexp: '(^/.*swap*)'
     replace: '# \1'

  - name: Creating a repository file for Kubernetes
    file:
     path: /etc/yum.repos.d/kubernetes.repo
     state: touch

  - name: Adding repository details in Kubernetes repo file.
    blockinfile:
     path: /etc/yum.repos.d/kubernetes.repo
     block: |
      [kubernetes]
      name=Kubernetes
      baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
      enabled=1
      gpgcheck=1
      repo_gpgcheck=1
      gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg
        https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg

  - name: add Docker repo
    shell: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

  - name: Install device-mapper-persistent-data , lvm2, firewalld, yum-utils, kubelet, kudebadm, kubectl, docker-ce
    yum:
     name: 
      - device-mapper-persistent-data
      - lvm2
      - firewalld 
      - yum-utils
      - kubelet 
      - kubeadm 
      - kubectl
      - docker-ce
     state: latest

  - name: Allow Network Ports in Firewalld
    firewalld:
     port: "{{ item }}"
     state: enabled
     permanent: yes
     immediate: yes
    with_items: "{{ ports }}"

  - name: Starting and Enabling the required services
    service:
     name: "{{ item }}"
     state: started
     enabled: yes
    with_items: "{{ services }}"

  - name: Enabling Bridge Firewall Rule
    shell: "echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables"
